name: smart-audio-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - librosa
  - tqdm
  - pip
  - pip:
      - torch
      - torchaudio
      - soundfile
